name: jQuery
version: 1.0.0
description: jQuery plugin for Flextype.
icon: fab fa-js-square
author:
  name: Sergey Romanenko
  email: support@flextype.org
  url: http://flextype.org
homepage: https://github.com/flextype-plugins/jquery
bugs: https://github.com/flextype-plugins/jquery/issues
license: MIT

dependencies:
  flextype: 0.9.7
